version: '3'
services:
  locales:
    build:
      context: .
      dockerfile: ./platforms/locales/Dockerfile
      target: dev
    restart: always
    command: >
      sh -c "
        mix setup &&
        mix phx.server
      "
    expose:
      - "4000"
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./services/locales:/app
    working_dir: /app
